// Generated by https://quicktype.io

export interface Chat {
    autor:     Autor;
    mensaje:   MensajeClass | string;
    timestamp: string;
}

export enum Autor {
    Cliente = "Cliente",
    Vendedor = "Vendedor",
}

export interface MensajeClass {
    nombre:    string;
    direccion: string;
    telefono:  string;
}
